# This is a sample GitHub Actions workflow file.
# To use it, create a '.github/workflows' directory in your repository
# and save this file as 'main.yml' inside it.

name: CI/CD Pipeline

# Controls when the action will run. 
# Triggers the workflow on push events but only for the main branch.
on:
  push:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "build-and-deploy"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      # This is a placeholder for your actual test command.
      # For example: 'npm test', 'docker-compose run app pytest', etc.
      # If this step fails, the entire pipeline will stop.
      run: echo "Running placeholder tests... Tests passed!"

    - name: Login to Docker Hub
      # This action logs into a container registry.
      # You must store DOCKERHUB_USERNAME and DOCKERHUB_TOKEN as secrets in your repository settings.
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      # This action builds the Docker image and pushes it to the registry.
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        # The image is tagged with the Git commit SHA for versioning.
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.sha }}

    - name: Deploy to server
      # This is a placeholder for your deployment strategy.
      # A common method is to SSH into a server and run a deployment script.
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # The script to run on the remote server
          echo "Deploying new version..."
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.sha }}
          # Example for Docker Compose. You might be using 'docker service update' for Swarm
          # or 'kubectl set image' for Kubernetes.
          docker-compose -f /path/to/your/docker-compose.yml up -d --no-deps my-app 
          echo "Deployment complete!"
