apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  PRODUCT_SERVICE_URL: "http://product-service.{{ .Values.global.namespace }}.svc.cluster.local"
  ORDER_SERVICE_URL: "http://order-service.{{ .Values.global.namespace }}.svc.cluster.local"
  ENABLE_FEATURE_X: "{{ .Values.config.enableFeatureX }}"
  UI_THEME: "{{ .Values.config.uiTheme }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  API_KEY: c3VwZXJzZWNyZXRrZXk=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <title>Kube Lifecycle Demo</title>
        <style>
            body { background-color: purple; color: white; text-align: center; padding: 50px; }
        </style>
    </head>
    <body>
        <h1>E-Commerce Platform</h1>
        <p>Managed by Helm</p>
    </body>
    </html>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    events { worker_connections 1024; }
    http {
        server {
            listen 80;
            location / { proxy_pass http://frontend; }
            location /product { proxy_pass http://product-service; }
            location /order { proxy_pass http://order-service; }
            location /healthz { return 200 'OK'; }
        }
    }
