apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend  # To apply over the existing one
  namespace: ecommerce
spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      priorityClassName: high-priority
      nodeSelector:
        tier: frontend
      tolerations:
      - key: "workload"
        operator: "Equal"
        value: "frontend"
        effect: "NoSchedule"
      containers:
      - name: frontend
        image: nginx:alpine
        env:
        - name: BACKEND_URL
          value: "http://backend:8080"
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
