# Use a lightweight Python base image
FROM python:3.11-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements-product-service.txt .
RUN pip install --no-cache-dir -r requirements-product-service.txt

# Copy the application code into the container
COPY product-service.py .

# Expose the port the app runs on
EXPOSE 5000

# Define the command to run the application
CMD ["python", "product-service.py"]
