# Use a lightweight Python base image
FROM python:3.11-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements-api-gateway.txt .
RUN pip install --no-cache-dir -r requirements-api-gateway.txt

# Copy the application code into the container
COPY api-gateway.py .

# Expose the port the app runs on
EXPOSE 3000

# Define the command to run the application
CMD ["python", "api-gateway.py"]
